[[CURRENCIES]]
code = "NXLX"
issuer = "GBCTTSQHGSEQUAFSHESWE22UOXKWZ4D34MGDTCL56JRPUL77WYI4SCPV"
name = "NEXLUX"
desc = "NEXLUX – A Controlled Digital Asset for Next-Level Financial Infrastructure"
image = "https://via.placeholder.com/512"
status = "active"
